name: Dev - CI

on:
  push:
    branches:
      - dev

jobs:
  build-linux:
    name: "Linux build"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: bazelbuild/setup-bazelisk@v3
      - name: Mount bazel cache
        uses: actions/cache@v4
        with:
          path: "/home/runner/.cache/bazel_linux"
          key: bazel
      - name: Test
        run: bazel test //...

  build-mac:
    name: "Mac OS build"
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4
    - uses: bazelbuild/setup-bazelisk@v3
    - name: Mount bazel cache
      uses: actions/cache@v4
      with:
        path: "/home/runner/.cache/bazel_osx"
        key: bazel
    - name: Test
      run: bazel test //...
